In [4]:
#we start with a 5 by 5 grid of spins

import numpy as np
import matplotlib.pyplot as plt
import random

#initialize the grid
def initialize_grid(n):
    grid = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            grid[i,j] = random.choice([-1,1])
    return grid

#test that the grid is initialized correctly
grid = initialize_grid(3)
print(grid)

[[ 1.  1.  1.]
 [ 1. -1.  1.]
 [-1.  1.  1.]]


In [6]:
#compute the energy of the grid
def compute_energy(grid):
    energy = 0
    n = len(grid)
    for i in range(n):
        for j in range(n):
            #check the energy at each point by selecting the nearest neighbors and checking whether they are the same spin
            energy += -grid[i,j]*(grid[(i+1)%n,j] + grid[i,(j+1)%n] + grid[(i-1)%n,j] + grid[i,(j-1)%n])
    return energy

#test that the energy is computed correctly
print(compute_energy(grid))

-4.0
